[package]
name = "day05"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2024"

[dependencies]
aoc-common = { path = "../aoc-common" }
itertools = "0.14.0"
tracing = "0.1.43"

[dev-dependencies]
rstest = "0.26.1"
